#Imports
import turtle as trtl
import random as rand

#Varibles
painter = trtl.Turtle()
painter.speed(0)

flowerx = rand.randint(-50,600)
flowery = rand.randint(-200,-125)


#functions for tree, ground, sky, flowers and clouds

def sky():
    painter.penup
    painter.color("sky blue")
    painter.pendown()
    painter.pensize(9000)
    painter.circle(9000)
    

#Creates The Ground
def ground():
    painter.speed(0)
    painter.penup()
    painter.goto(300,-1450)
    painter.pencolor("green")
    painter.fillcolor("green")
    painter.pendown()
    painter.pensize(2000)
    painter.circle(200)


#Creates Tree Trunk
def tree_trunk():
    painter.penup()
    painter.pensize(5)
    painter.color("burlywood4")
    painter.fillcolor("burlywood4")
    painter.goto(200,-125)
    painter.setheading(0)
    painter.pendown()
    painter.circle(100,80)
    painter.penup()
    painter.goto(300,-125)
    painter.setheading(-0)
    painter.circle(100,80)
    painter.setheading(280)
    painter.pendown()
    painter.circle(100,80)
    painter.penup()
    painter.goto(297,-40)
    painter.setheading(90)
    painter.pendown()
    painter.forward(200)
    painter.penup()
    painter.goto(397,-40)
    painter.pendown()
    painter.forward(200)
    painter.penup()
    painter.goto(200,-125)
    painter.setheading(0)
    painter.pendown()
    painter.forward(300)
    painter.penup()
    painter.goto(347,160)
    painter.pensize(100)
    painter.shape("square")
    painter.setheading(270)
    painter.pendown()
    painter.forward(235)
    painter.penup()
    painter.goto(350,-65)
    painter.pensize(50)
    painter.setheading(0)
    painter.pendown()
    painter.forward(30)
    painter.penup()
    painter.setheading(270)
    painter.pensize(40)
    painter.pendown()
    painter.forward(40)
    painter.penup()
    painter.goto(315,-65)
    painter.setheading(270)
    painter.pensize(40)
    painter.pendown()
    painter.forward(40)
    painter.goto(305,-80)
    painter.setheading(0)
    painter.pensize(40)
    painter.pendown()
    painter.forward(85)
    painter.goto(285,-105)
    painter.setheading(0)
    painter.pensize(40)
    painter.pendown()
    painter.forward(125)
    painter.penup()
    painter.goto(290,-90)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(404.5,-85)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.pensize(30)
    painter.goto(271,-113)
    painter.pendown()
    painter.forward(156)
    painter.penup()
    painter.goto(260,-115)
    painter.turtlesize(.7)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(250,-120)
    painter.turtlesize(.7)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(240,-120)
    painter.turtlesize(.4)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(235,-120)
    painter.turtlesize(.3)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(440,-118)
    painter.turtlesize(.8)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(450,-118)
    painter.turtlesize(.5)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(459,-120)
    painter.turtlesize(.4)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.goto(462,-122)
    painter.turtlesize(.3)
    painter.pendown()
    painter.stamp()





#Creates Tree Leaves
def tree_leaves():
    painter.color("lime")
    painter.penup()
    painter.turtlesize(5)
    painter.shape("circle")
    painter.goto(347,160)
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.goto(347,160)
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(25)
    painter.right(90)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(180)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(25)
    painter.left(90)
    painter.forward(50)
    painter.setheading(0)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()
    painter.penup()
    painter.setheading(0)
    painter.forward(50)
    painter.pendown()
    painter.stamp()




def all_flowers():
    flowers = 50
    flowerx = rand.randint(-180,180)
    flowery = rand.randint(-200,-125)
    while flowers > 0:
        painter.turtlesize(.5)
        painter.penup()
        painter.fillcolor("violet")
        flowerx = rand.randint(-100,600)
        flowery = rand.randint(-300,-140)
        painter.goto(flowerx,flowery)
        painter.pendown()
        painter.stamp()
        flowers = flowers - 1
        


def moving_clouds():
    my_turtles = []

    turtle_shapes = ["arrow", "turtle", "circle", "square", "triangle", "classic"]
    for s in turtle_shapes:
        t = trtl.Turtle(shape=s)
        t.color("white")
        my_turtles.append(t)

    


    clouds = 0
    while (clouds < 6):
         for t in my_turtles:
            t.penup()
            t.speed(0)
            t.goto(500,500)

         for t in my_turtles:
            t.penup()
            t.speed(0)
            t.goto(500, 400)
            t.speed(1)
            t.setheading(180)
            t.turtlesize(4)
            t.showturtle
            t.circle(1100,180)
            


    
sky()
ground()
tree_trunk()
tree_leaves()
all_flowers()
moving_clouds()

wn = trtl.Screen()
wn.mainloop()
